---
- name: Installs packages
  become: yes
  become_method: sudo
  user: centos
  hosts: all
  tasks:
  - name: Install Telnet
    package:
      name: "{{item}}"
      state: present
    with_items:
    - telnet
    - gzip
    - lftp
    - httpd
    - vsftpd
