---
- name: User Playbook
  become: yes
  become_method: sudo
  user: centos
  hosts: all
  tasks:
  - name: user add bob
    user:
      name: bob
      comment: "John Smith"
      groups: wheel
      generate_ssh_key: yes
      state: present

  - name: user add lisa
    user:
      name: lisa
      state: absent

  - name: user add sam
    user:
      name: sam
      state: absent